import type { Difficulty, ProjectTheme } from './types';
import { jukuOverrides, hospitalOverrides, bankOverrides } from './themedScenarios';

export type DifficultyConfig = {
  id: Difficulty;
  label: string;
  weeks: number;
  phaseCount: number;
  scenariosPerPhase: number;
  effectMultiplier: number;
  eventProbability: number;
  teamSize: number;
  useMaintPhases?: boolean;
  usePmoPhases?: boolean;
  useMemberPhases?: boolean;
  initialStats: {
    quality: number;
    cost: number;
    schedule: number;
    stakeholder: number;
    morale: number;
    pmMental: number;
  };
  description: string;
  badge: string;
  color: string;
  unlockCondition?: { difficulty: Difficulty; minScore: number; label: string };
};

export const difficultyConfigs: Record<Difficulty, DifficultyConfig> = {
  easy: {
    id: 'easy',
    label: 'イージー',
    weeks: 15,
    phaseCount: 3,
    scenariosPerPhase: 2,
    effectMultiplier: 0.55,
    eventProbability: 0,
    teamSize: 5,
    initialStats: { quality: 82, cost: 88, schedule: 65, stakeholder: 78, morale: 83, pmMental: 88 },
    description: '初めてPMの仕事を体験する入門モード。5人チーム、突発イベントなし、判断ミスの影響も小さいです。',
    badge: '入門',
    color: 'emerald',
  },
  normal: {
    id: 'normal',
    label: 'ノーマル',
    weeks: 30,
    phaseCount: 5,
    scenariosPerPhase: 5,
    effectMultiplier: 1.0,
    eventProbability: 0.42,
    teamSize: 10,
    initialStats: { quality: 72, cost: 80, schedule: 48, stakeholder: 67, morale: 72, pmMental: 75 },
    description: '現場に近い難易度。10人チームで突発事象が発生し、QCDのバランス管理が求められます。',
    badge: '標準',
    color: 'blue',
  },
  hard: {
    id: 'hard',
    label: 'ハード',
    weeks: 50,
    phaseCount: 5,
    scenariosPerPhase: 6,
    effectMultiplier: 1.45,
    eventProbability: 0.68,
    teamSize: 20,
    initialStats: { quality: 63, cost: 68, schedule: 33, stakeholder: 58, morale: 62, pmMental: 62 },
    description: '20人の大規模チーム。判断ミスの連鎖が炎上を招き、プロジェクト崩壊のリスクが常にあります。',
    badge: '上級',
    color: 'orange',
  },
  ultra: {
    id: 'ultra',
    label: 'ウルトラ',
    weeks: 200,
    phaseCount: 10,
    scenariosPerPhase: 5,
    effectMultiplier: 1.7,
    eventProbability: 0.78,
    teamSize: 50,
    initialStats: { quality: 55, cost: 60, schedule: 25, stakeholder: 50, morale: 55, pmMental: 55 },
    description: '50人の超大規模チームで200週の旅。運用移行・組織変革・レガシー刷新。炎上は避けられない前提。',
    badge: '超上級',
    color: 'violet',
    unlockCondition: { difficulty: 'hard', minScore: 75, label: 'ハードモードをスコア75以上でクリア' },
  },
  'maint-easy': {
    id: 'maint-easy',
    label: '保守運用 Easy',
    weeks: 24,
    phaseCount: 3,
    scenariosPerPhase: 3,
    effectMultiplier: 0.65,
    eventProbability: 0.35,
    teamSize: 5,
    useMaintPhases: true,
    initialStats: { quality: 68, cost: 75, schedule: 72, stakeholder: 58, morale: 65, pmMental: 78 },
    description: '既存システムの保守・障害対応が中心。SLA遵守と技術的負債との戦い。5人の少数精鋭チーム。',
    badge: '保守 入門',
    color: 'teal',
  },
  'maint-hard': {
    id: 'maint-hard',
    label: '保守運用 Hard',
    weeks: 52,
    phaseCount: 5,
    scenariosPerPhase: 5,
    effectMultiplier: 1.4,
    eventProbability: 0.62,
    teamSize: 20,
    useMaintPhases: true,
    initialStats: { quality: 58, cost: 62, schedule: 65, stakeholder: 45, morale: 55, pmMental: 60 },
    description: '大規模システムの24時間運用。深夜障害・SLA超過・レガシー刷新を同時に回す20人体制。',
    badge: '保守 上級',
    color: 'teal',
  },
  'pmo-support': {
    id: 'pmo-support',
    label: 'PMO 支援型',
    weeks: 36,
    phaseCount: 5,
    scenariosPerPhase: 3,
    effectMultiplier: 1.0,
    eventProbability: 0.45,
    teamSize: 8,
    usePmoPhases: true,
    initialStats: { quality: 50, cost: 80, schedule: 55, stakeholder: 55, morale: 60, pmMental: 40 },
    description: '提案・説得しかできない支援型PMO。現場信頼度を地道に積み上げ、協力を引き出すスタイル。8人体制。',
    badge: 'PMO 支援',
    color: 'indigo',
  },
  'pmo-control': {
    id: 'pmo-control',
    label: 'PMO 統制型',
    weeks: 52,
    phaseCount: 5,
    scenariosPerPhase: 3,
    effectMultiplier: 1.2,
    eventProbability: 0.55,
    teamSize: 15,
    usePmoPhases: true,
    initialStats: { quality: 45, cost: 75, schedule: 48, stakeholder: 50, morale: 55, pmMental: 35 },
    description: 'フレームワーク遵守を要求し是正権限を持つ統制型PMO。逸脱があれば改善を迫れる。15人体制。',
    badge: 'PMO 統制',
    color: 'indigo',
  },
  'pmo-directive': {
    id: 'pmo-directive',
    label: 'PMO 指揮型',
    weeks: 60,
    phaseCount: 5,
    scenariosPerPhase: 3,
    effectMultiplier: 1.4,
    eventProbability: 0.65,
    teamSize: 25,
    usePmoPhases: true,
    initialStats: { quality: 40, cost: 70, schedule: 42, stakeholder: 45, morale: 50, pmMental: 30 },
    description: '中止命令・投資承認権を持つ指揮型PMO。強い権限があるが乱用すると現場信頼度が崩壊する。25人体制。',
    badge: 'PMO 指揮',
    color: 'indigo',
  },
  'ops-easy': {
    id: 'ops-easy',
    label: 'メンバー Easy',
    weeks: 20,
    phaseCount: 3,
    scenariosPerPhase: 3,
    effectMultiplier: 0.6,
    eventProbability: 0.15,
    teamSize: 6,
    useMemberPhases: true,
    initialStats: { quality: 78, cost: 90, schedule: 72, stakeholder: 76, morale: 78, pmMental: 82 },
    description: '定常業務と軽い問い合わせ対応が中心。深夜呼び出しほぼなし。まず運用の流れを体験する入門モード。',
    badge: 'メンバー 入門',
    color: 'teal',
  },
  'ops-normal': {
    id: 'ops-normal',
    label: 'メンバー Normal',
    weeks: 36,
    phaseCount: 4,
    scenariosPerPhase: 4,
    effectMultiplier: 1.0,
    eventProbability: 0.45,
    teamSize: 6,
    useMemberPhases: true,
    initialStats: { quality: 70, cost: 80, schedule: 62, stakeholder: 68, morale: 65, pmMental: 70 },
    description: '深夜アラート・繰り返す障害・属人化のリアルを体験する。判断ミスが積み重なるとSLAが崩れていく。',
    badge: 'メンバー 標準',
    color: 'teal',
  },
  'ops-hard': {
    id: 'ops-hard',
    label: 'メンバー Hard',
    weeks: 52,
    phaseCount: 4,
    scenariosPerPhase: 4,
    effectMultiplier: 1.5,
    eventProbability: 0.65,
    teamSize: 6,
    useMemberPhases: true,
    initialStats: { quality: 58, cost: 65, schedule: 52, stakeholder: 55, morale: 50, pmMental: 58 },
    description: 'すでに疲弊気味の状態でスタート。SLA超過ギリギリ・オンコール過多・属人化が進んだ限界の現場。',
    badge: 'メンバー 上級',
    color: 'teal',
  },
};

export const projectThemes: Record<Difficulty, ProjectTheme[]> = {
  easy: [
    {
      id: 'restaurant-order',
      title: '飲食チェーンの注文管理システム',
      client: '株式会社ハーベスト（都内10店舗の洋食チェーン）',
      description: '紙の注文票からデジタル化へ。シンプルな構成で小規模チームが対応。',
      statModifiers: { morale: 5 },
    },
    {
      id: 'juku-grade',
      title: '学習塾の成績・進捗管理アプリ',
      client: 'あすなろ学習院（生徒500名の個別指導塾）',
      description: '講師と保護者が使いやすい成績管理ツール。予算は少ないが要件はシンプル。',
      statModifiers: { cost: -8, stakeholder: 5 },
      overrides: jukuOverrides,
    },
    {
      id: 'realestate-db',
      title: '不動産仲介会社の物件管理DB',
      client: 'ミライホーム不動産（地域密着の中小企業）',
      description: 'Excelで管理していた物件情報をシステム化。操作が簡単なことが最優先。',
      statModifiers: { morale: 3, cost: -5 },
    },
    {
      id: 'library-renewal',
      title: '地域図書館の蔵書・貸出管理更新',
      client: '市立中央図書館（公共施設）',
      description: '老朽化したシステムの更新。公共調達のため変更は少ないが意思決定が遅い。',
      statModifiers: { schedule: -5, stakeholder: 8 },
    },
    {
      id: 'salon-booking',
      title: '美容院チェーンの予約・顧客管理',
      client: 'ヘアーサロン「ルーチェ」（15店舗展開）',
      description: '電話予約からオンライン予約への移行。現場スタッフの使いやすさが鍵。',
      statModifiers: { morale: 5, stakeholder: 3 },
    },
  ],
  normal: [
    {
      id: 'retail-inventory',
      title: '中堅小売チェーンの在庫管理システム',
      client: '株式会社マルタカリテール（スーパー28店舗）',
      description: '在庫のリアルタイム可視化と発注自動化。業務改善の期待が高い。',
      statModifiers: {},
    },
    {
      id: 'manufacturing-quality',
      title: '製造業の品質管理・検査システム',
      client: '東洋精機株式会社（自動車部品メーカー）',
      description: '紙の検査記録をデジタル化し、品質トレーサビリティを確保する。',
      statModifiers: { quality: 5, stakeholder: -3 },
    },
    {
      id: 'hospital-reception',
      title: '中堅病院の予約・受付・会計システム',
      client: '医療法人みなと病院（200床・外来1日400名）',
      description: '医療システムはコンプライアンスが厳しく、稼働後の変更が難しい。',
      statModifiers: { stakeholder: 8, schedule: -5 },
      overrides: hospitalOverrides,
    },
    {
      id: 'logistics-delivery',
      title: '物流会社の配送管理プラットフォーム',
      client: '全国通運株式会社（関東圏の中堅物流）',
      description: 'ドライバー・倉庫・顧客が連携するリアルタイム配送管理システム。',
      statModifiers: { cost: -5, morale: -3 },
    },
    {
      id: 'ec-order-integration',
      title: 'EC企業の受注・在庫統合管理システム',
      client: '株式会社ネクストショップ（年商30億のEC企業）',
      description: '複数モールの受注を一元管理。システム障害が直接売上に影響する。',
      statModifiers: { quality: 3, schedule: -5 },
    },
  ],
  hard: [
    {
      id: 'dept-store-core',
      title: '大手百貨店の基幹システム全面刷新',
      client: '帝都百貨店株式会社（年商3,000億・6店舗）',
      description: '30年稼働する既存基幹システムを全面刷新。失敗は許されない大型案件。',
      statModifiers: { quality: -5, stakeholder: 5 },
    },
    {
      id: 'bank-online',
      title: '地方銀行の勘定系サブシステム刷新',
      client: '第一東海地方銀行（口座数80万・支店数38）',
      description: '25年稼働する勘定系サブシステムの世代交代。金融庁規制対応と多重ベンダー管理が最難関。',
      statModifiers: { quality: 5, morale: -8, schedule: -8 },
      overrides: bankOverrides,
    },
    {
      id: 'ec-nationwide',
      title: '全国展開ECサイトの大規模構築',
      client: '株式会社グランドモール（上場EC企業）',
      description: 'ピーク時数十万アクセスを処理するECプラットフォームをゼロから構築。',
      statModifiers: { cost: -8, morale: -5 },
    },
    {
      id: 'gov-dx',
      title: '自治体DXプロジェクト（行政手続き電子化）',
      client: '関東圏A市（人口35万人・市役所）',
      description: '行政特有の縦割り組織と厳しい調達規制の中で市民サービスを改善する。',
      statModifiers: { schedule: -10, stakeholder: 8, morale: -5 },
    },
    {
      id: 'global-erp',
      title: 'グローバル製造業のERP全社導入',
      client: '株式会社サンライズマニュファクチャリング（海外6拠点）',
      description: '国内外10拠点に渡るERPの展開。文化・言語・時差の壁を超えた調整が必要。',
      statModifiers: { cost: -10, stakeholder: -5, morale: -5 },
    },
  ],
  ultra: [
    {
      id: 'city-bank-core',
      title: '大手都市銀行の勘定系システム完全刷新',
      client: '太平洋銀行（口座数5,000万・国内最大級）',
      description: '国内最大規模の金融基盤を200週かけて世代交代。国家経済に影響しかねない。',
      statModifiers: { quality: -5, stakeholder: 8, morale: -8 },
    },
    {
      id: 'mega-ec-replatform',
      title: '国内最大手ECモールのフルリプレイス',
      client: '株式会社ジャパンモール（流通総額2兆円）',
      description: '日本最大のECプラットフォームを停止ゼロで全面刷新。失敗は即座に社会問題化する。',
      statModifiers: { cost: -8, schedule: -8 },
    },
    {
      id: 'hospital-chain-emr',
      title: '全国チェーン病院の統合電子カルテ構築',
      client: '医療法人アドバンスケア（全国100病院・2万床）',
      description: '患者の命に直結する医療情報システム。コンプライアンスと品質が絶対条件。',
      statModifiers: { quality: -8, stakeholder: 10 },
    },
    {
      id: 'national-digital-id',
      title: '国家レベルのデジタルIDプラットフォーム',
      client: '内閣府デジタル庁（国民1億2000万人が対象）',
      description: '全国民が使う認証基盤。政治的圧力・予算制約・セキュリティ要件が極限レベル。',
      statModifiers: { schedule: -10, stakeholder: 5, morale: -8 },
    },
    {
      id: 'connected-car',
      title: '自動車メーカーのコネクテッドカーPF構築',
      client: '日本モーター株式会社（世界シェア5位の自動車メーカー）',
      description: '走行中の車両と繋がるクラウド基盤。OTAアップデート・AI解析・グローバル展開を含む。',
      statModifiers: { cost: -10, quality: -5, morale: -5 },
    },
  ],
  'maint-easy': [
    {
      id: 'maint-easy-juku',
      title: '学習塾システムの保守・問い合わせ対応',
      client: 'あすなろ学習院（生徒500名の個別指導塾）',
      description: '成績管理・出欠システムの定常保守。月1回の定期メンテと講師からの問い合わせ対応が主業務。',
      category: '保守運用',
      statModifiers: { morale: 3 },
    },
    {
      id: 'maint-easy-ec',
      title: '小規模ECサイトの運用・障害対応',
      client: '手作り雑貨「てのひらマーケット」（月商200万円）',
      description: '注文・在庫・配送システムの日次確認と障害対応。深夜に突然電話が来ることも。',
      category: '保守運用',
      statModifiers: { morale: -4, stakeholder: -5 },
    },
    {
      id: 'maint-easy-realestate',
      title: '不動産管理システムの保守・改善要望対応',
      client: 'ミライホーム不動産（地域密着の中小企業）',
      description: '物件DB・顧客管理システムの保守。改善要望は多いが予算は厳しく、優先度判断が常に求められる。',
      category: '保守運用',
      statModifiers: { cost: -5, schedule: 5 },
    },
    {
      id: 'maint-easy-groupware',
      title: '社内グループウェアの運用管理',
      client: 'ある中小製造業（社員150名）',
      description: '社内メール・スケジュール・ファイル共有の日常管理。地味だが誰かが怠ると全社に影響が出る。',
      category: '保守運用',
      statModifiers: { schedule: 8, morale: -6 },
    },
    {
      id: 'maint-easy-library',
      title: '地域図書館システムの保守・年次更新',
      client: '市立中央図書館（公共施設）',
      description: '蔵書・貸出管理システムの保守と年次ライセンス更新。予算が少なく、無償対応を求められがち。',
      category: '保守運用',
      statModifiers: { cost: -8, stakeholder: -3, schedule: 5 },
    },
  ],
  'maint-hard': [
    {
      id: 'maint-hard-securities',
      title: '証券会社 夜間バッチ・障害対応運用',
      client: '東洋証券株式会社（口座数150万）',
      description: '毎日深夜に走る約定・清算バッチの監視。障害が市場開場前に解決されなければ損失が直撃する。',
      category: '保守運用',
      statModifiers: { morale: -8, stakeholder: -8, cost: -5 },
    },
    {
      id: 'maint-hard-factory',
      title: '大手製造業 生産管理システム 24h運用保守',
      client: '東洋精機株式会社（自動車部品メーカー）',
      description: '24時間稼働の生産ラインを支えるシステム。ダウンタイムは1分で数百万の損失。改善要望も絶えない。',
      category: '保守運用',
      statModifiers: { morale: -6, stakeholder: -7, quality: -5 },
    },
    {
      id: 'maint-hard-hospital',
      title: '中堅病院グループ 電子カルテシステム保守',
      client: '医療法人みなと病院グループ（3病院・500床）',
      description: '複数拠点の電子カルテ・オーダリングシステムの24h運用。障害は患者の命に関わる可能性がある。',
      category: '保守運用',
      statModifiers: { morale: -7, stakeholder: -6, quality: -4 },
    },
    {
      id: 'maint-hard-bank',
      title: '地方銀行 勘定系・インターネットバンキング保守',
      client: '東海地方銀行（支店数80・口座数50万）',
      description: '勘定系とネットバンキングの保守。障害は即座に金融庁報告義務が発生し、社会的信用が毀損する。',
      category: '保守運用',
      statModifiers: { morale: -8, stakeholder: -8, cost: -6, quality: -3 },
    },
    {
      id: 'maint-hard-logistics',
      title: '全国物流会社の配送管理プラットフォーム保守',
      client: '全国通運株式会社（ドライバー3000名）',
      description: '全国のドライバー・倉庫・顧客をつなぐシステムの保守。年末年始・お盆の繁忙期に必ず障害が起きる。',
      category: '保守運用',
      statModifiers: { morale: -5, stakeholder: -6, cost: -4 },
    },
  ],
  'pmo-support': [
    { id: 'pmos-sier-admin', title: 'SIerのプロジェクト事務局PMO', client: '大手SIer A社（PJ数12件・IT部門内PMO）', description: '各PMの報告書整理・定例運営・ツール管理が中心。まだ権限は弱く、現場からは「お役所的」と見られがち。', category: 'PMO', statModifiers: { stakeholder: -5, morale: -5 } },
    { id: 'pmos-inhouse', title: '中堅IT企業の内製化支援PMO', client: '株式会社テクノソリューション（社員300名）', description: 'PM経験のない社員がPJを担当しており、PMO支援で底上げを図る。信頼関係ゼロからのスタート。', category: 'PMO', statModifiers: { schedule: -5, morale: -3 } },
    { id: 'pmos-education', title: '教育機関DX推進PMO', client: '関東圏の私立大学（学生数8000名）', description: '教職員は変化を嫌い、IT部門は弱体化している。PMOとして外部知識で内部を動かす高難度の支援型。', category: 'PMO', statModifiers: { schedule: -6, stakeholder: -4, morale: -3 } },
    { id: 'pmos-startup', title: 'スタートアップのプロジェクト管理改善PMO', client: '急成長SaaS企業（従業員80名）', description: '組織が急拡大する中でPJ管理がカオス状態。スピードを損なわず標準化するバランスが求められる。', category: 'PMO', statModifiers: { cost: -5, quality: -5 } },
    { id: 'pmos-municipal', title: '地方自治体の情報化PMO支援', client: '関東圏A市（人口20万）', description: '縦割り組織と意思決定の遅さが最大の壁。行政特有の制約の中で横断的な標準化を進める。', category: 'PMO', statModifiers: { schedule: -8, morale: -5 } },
  ],
  'pmo-control': [
    { id: 'pmoc-sier-cross', title: '大手SIer 複数PJ横断統制PMO', client: '大手SIer B社（PJ数25件・PMO部門20名）', description: '報告基準・ガバナンスの統制を持つ。プロジェクトの逸脱に是正要求を出せるが現場との衝突も多い。', category: 'PMO', statModifiers: { stakeholder: -6, morale: -4 } },
    { id: 'pmoc-manufacturing-dx', title: '製造業 全社DXプログラムPMO', client: '東洋精機株式会社（従業員5000名）', description: '生産・物流・販売の3領域を横断するDXプログラム。PJ間の依存関係管理と優先度調整が中心業務。', category: 'PMO', statModifiers: { cost: -5, schedule: -5 } },
    { id: 'pmoc-finance', title: '金融機関 システム刷新PMO', client: '東海地方銀行（支店80・口座50万）', description: '金融庁規制対応と旧システム刷新を並行するPMO。コンプライアンス要件が最優先で変更管理が厳格。', category: 'PMO', statModifiers: { quality: -5, stakeholder: -5 } },
    { id: 'pmoc-hospital', title: '医療法人 IT基盤整備統制PMO', client: '医療法人みなと病院グループ（3病院）', description: '患者データの取り扱いに関わるため品質基準が最高レベル。PMOが次工程移行の承認権を持つ。', category: 'PMO', statModifiers: { morale: -5, quality: -4 } },
    { id: 'pmoc-retail', title: '小売業 全社基幹システム統一PMO', client: '株式会社マルタカHD（グループ5社・店舗200）', description: 'グループ各社が独自システムを持ち、統一に向けて各社PMとの利害調整が複雑。指揮権なき調整が腕の見せ所。', category: 'PMO', statModifiers: { schedule: -6, stakeholder: -4 } },
  ],
  'pmo-directive': [
    { id: 'pmod-gov-dx', title: '政府系 DX推進 指揮型PMO', client: '内閣府DX推進室（全省庁横断）', description: '複数省庁に対して方針・予算・スケジュールを指揮できる。政治的圧力と官僚組織の抵抗が最大の壁。', category: 'PMO', statModifiers: { schedule: -8, stakeholder: -6 } },
    { id: 'pmod-bank-group', title: '大手銀行 グループIT戦略PMO', client: '太平洋銀行グループ（傘下12社・IT予算500億）', description: 'IT投資の承認権を持つ最上位PMO。ROIに基づくPJ選定・中止判断が主業務。政治力との戦い。', category: 'PMO', statModifiers: { cost: -6, morale: -5 } },
    { id: 'pmod-pharma', title: '製薬会社 グローバルシステム統合PMO', client: '日本製薬株式会社（海外拠点15カ国）', description: '海外拠点のシステムを統合する指揮型PMO。文化・言語・規制の違いをまたいで標準化を強制する。', category: 'PMO', statModifiers: { cost: -8, schedule: -6 } },
    { id: 'pmod-consulting', title: '大手コンサルファーム 参謀型PMO', client: '外資系コンサルティングファーム（クライアント企業向け）', description: '経営直結の意思決定支援PMO。ROI・リスク・組織能力を統合判断し経営層に直接提言する最高峰。', category: 'PMO', statModifiers: { stakeholder: -5, quality: -5 } },
    { id: 'pmod-portfolio', title: '全社IT投資判断・ポートフォリオPMO', client: 'ある大手総合商社（IT投資年間300億）', description: '全PJの継続・中止・追加投資を判断する。現場から「恐怖の砦」と呼ばれないよう権限の使い方が問われる。', category: 'PMO', statModifiers: { morale: -8, stakeholder: -5 } },
  ],
  'ops-easy': [
    { id: 'ops-easy-intranet', title: '社内グループウェア 運用サポート', client: '中堅製造業 情報システム部（社員300名）', description: '社内ツールのヘルプデスク対応・定期メンテが中心。大きな障害は少なく、業務時間内の対応がほとんど。', statModifiers: { morale: 5 } },
    { id: 'ops-easy-erp', title: '中小企業 基幹ERPの保守', client: '株式会社ミタカ産業（従業員120名・製造業）', description: '既存ERPの月次バッチ管理と操作サポート。システムは安定しており、スキルアップの基礎を固める現場。', statModifiers: { cost: 5 } },
    { id: 'ops-easy-portal', title: '社内ポータルサイト 運用管理', client: '都内サービス業 IT推進室（社員500名）', description: 'コンテンツ更新・アカウント管理・問い合わせ対応が日常業務。障害は少なく、手順化しやすい環境。', statModifiers: { stakeholder: 5 } },
  ],
  'ops-normal': [
    { id: 'ops-normal-banking', title: '銀行基幹システム 夜間バッチ運用', client: '第一信用銀行（口座数800万）', description: '毎晩数百本のバッチが走り、失敗すれば翌朝業務が止まる。深夜監視・障害対応が日常の金融系運用現場。', statModifiers: { schedule: -5, morale: -5 } },
    { id: 'ops-normal-ec', title: 'ECサイト インフラ・障害対応', client: 'ショッピングモールOnnet（月間1,000万UU）', description: 'セール期間の急激なトラフィック・決済障害。24時間監視が必要な高負荷ECプラットフォーム運用。', statModifiers: { stakeholder: -5, cost: -5 } },
    { id: 'ops-normal-hospital', title: '病院電子カルテ 保守・サポート', client: '東都総合医療センター（病床800・外来1日600人）', description: '医師・看護師が日中使い続けるシステム。停止は患者対応に直結するため、メンテ時間が限られる高責任運用。', statModifiers: { quality: -5, schedule: -5 } },
    { id: 'ops-normal-logistics', title: '物流管理システム 24h運用', client: '全国配送株式会社（拠点200・日次出荷10万件）', description: '深夜の出荷データ連携・翌朝の集計バッチが核心。1件のデータ不整合が全国の配送に波及する精密運用現場。', statModifiers: { morale: -5, cost: -5 } },
  ],
  'ops-hard': [
    { id: 'ops-hard-fintech', title: '決済プラットフォーム 24h対応', client: 'FinPay株式会社（加盟店5万店・決済処理秒間3,000件）', description: '1分の停止が数千万円の損失。セキュリティインシデント・不正検知・SLA99.99%という極限環境の運用現場。', statModifiers: { schedule: -8, morale: -8, cost: -5 } },
    { id: 'ops-hard-telecom', title: '通信インフラ 基盤運用', client: '全国通信キャリア 設備管理部門', description: '数千台のサーバを少人数で管理。オンコール当番が重く、レガシーと最新設備が混在する難易度最高の現場。', statModifiers: { quality: -8, stakeholder: -5, morale: -8 } },
    { id: 'ops-hard-gov', title: '自治体システム 統合保守', client: '大都市圏 政令指定都市（住民250万人）', description: '住民サービスに直結するシステムを複数並行保守。予算制約・レガシーの山・政治的プレッシャーが重なる過酷環境。', statModifiers: { cost: -8, schedule: -8, morale: -5 } },
  ],
};
