import type { TeamMember } from './types';

// Full pool of 50 members. Sliced by difficulty: easy=5, normal=10, hard=20, ultra=50
export const allTeamMembers: TeamMember[] = [
  // ── Easy core (m1–m5) ─────────────────────────────────────────────
  { id: 'm1',  name: '田中 誠',     affiliation: '自社プロパー', role: 'PL',       skillLevel: 5, experienceYears: 12, specialty: '要件定義',   weakness: '詳細設計',   costPerMonth: 140, utilization: 0, condition: 88, motivation: 92, isSiloed: false, reportedProgress: 50, actualProgress: 45 },
  { id: 'm2',  name: '鈴木 美咲',   affiliation: '自社プロパー', role: 'SE',       skillLevel: 4, experienceYears:  7, specialty: '設計',       weakness: 'テスト',     costPerMonth: 110, utilization: 0, condition: 82, motivation: 76, isSiloed: false, reportedProgress: 40, actualProgress: 35 },
  { id: 'm3',  name: '遠藤 翔',     affiliation: '協力会社A',   role: 'PG',       skillLevel: 3, experienceYears:  4, specialty: '実装',       weakness: '顧客対応',   costPerMonth:  95, utilization: 0, condition: 74, motivation: 68, isSiloed: true,  reportedProgress: 55, actualProgress: 40 },
  { id: 'm4',  name: '高橋 奈緒',   affiliation: 'SES（客先常駐）', role: 'テスター', skillLevel: 2, experienceYears:  2, specialty: '検証',       weakness: '設計理解',   costPerMonth:  85, utilization: 0, condition: 66, motivation: 62, isSiloed: false, reportedProgress: 30, actualProgress: 28 },
  { id: 'm5',  name: '山田 太郎',   affiliation: '自社プロパー', role: 'SE',       skillLevel: 4, experienceYears:  8, specialty: '外部設計',   weakness: 'コスト管理', costPerMonth: 108, utilization: 0, condition: 85, motivation: 80, isSiloed: false, reportedProgress: 45, actualProgress: 42 },

  // ── Normal add (m6–m10) ───────────────────────────────────────────
  { id: 'm6',  name: '村上 由美子', affiliation: '自社プロパー', role: 'アナリスト', skillLevel: 4, experienceYears:  9, specialty: '業務分析',   weakness: '技術詳細',   costPerMonth: 112, utilization: 0, condition: 80, motivation: 74, isSiloed: false, reportedProgress: 50, actualProgress: 46 },
  { id: 'm7',  name: '中村 健',     affiliation: '協力会社B',   role: 'PG',       skillLevel: 3, experienceYears:  3, specialty: '実装',       weakness: '設計',       costPerMonth:  90, utilization: 0, condition: 70, motivation: 55, isSiloed: false, reportedProgress: 40, actualProgress: 30 },
  { id: 'm8',  name: '前田 真由美', affiliation: 'SES（客先常駐）', role: 'テスター', skillLevel: 2, experienceYears:  1, specialty: '検証',       weakness: '自動化',     costPerMonth:  80, utilization: 0, condition: 60, motivation: 58, isSiloed: false, reportedProgress: 35, actualProgress: 22 },
  { id: 'm9',  name: '小林 拓也',   affiliation: '自社プロパー', role: 'インフラ',  skillLevel: 4, experienceYears:  6, specialty: 'インフラ設計', weakness: 'ドキュメント', costPerMonth: 115, utilization: 0, condition: 84, motivation: 78, isSiloed: false, reportedProgress: 45, actualProgress: 43 },
  { id: 'm10', name: '伊藤 雅人',   affiliation: '協力会社A',   role: 'SE',       skillLevel: 3, experienceYears:  5, specialty: '詳細設計',   weakness: '顧客折衝',   costPerMonth:  95, utilization: 0, condition: 72, motivation: 65, isSiloed: true,  reportedProgress: 50, actualProgress: 38 },

  // ── Hard add (m11–m20) ────────────────────────────────────────────
  { id: 'm11', name: '渡辺 浩二',   affiliation: '協力会社B',   role: 'PG',       skillLevel: 2, experienceYears:  2, specialty: 'フロントエンド', weakness: 'テスト',   costPerMonth:  82, utilization: 0, condition: 58, motivation: 50, isSiloed: false, reportedProgress: 45, actualProgress: 28 },
  { id: 'm12', name: '佐々木 誠',   affiliation: '自社プロパー', role: 'PL',       skillLevel: 5, experienceYears: 15, specialty: 'プロジェクト管理', weakness: '新技術',  costPerMonth: 145, utilization: 0, condition: 76, motivation: 62, isSiloed: false, reportedProgress: 55, actualProgress: 50 },
  { id: 'm13', name: '斎藤 大輔',   affiliation: '協力会社A',   role: 'DBA',      skillLevel: 4, experienceYears: 10, specialty: 'DB設計',     weakness: 'UI/UX',    costPerMonth: 118, utilization: 0, condition: 78, motivation: 70, isSiloed: false, reportedProgress: 50, actualProgress: 46 },
  { id: 'm14', name: '松本 和也',   affiliation: 'SES（客先常駐）', role: 'PG',    skillLevel: 2, experienceYears:  2, specialty: 'バックエンド', weakness: '設計理解', costPerMonth:  80, utilization: 0, condition: 55, motivation: 48, isSiloed: true,  reportedProgress: 40, actualProgress: 22 },
  { id: 'm15', name: '宮本 麻衣',   affiliation: '自社プロパー', role: 'QA',       skillLevel: 3, experienceYears:  5, specialty: '品質保証',   weakness: '開発コード', costPerMonth:  98, utilization: 0, condition: 80, motivation: 73, isSiloed: false, reportedProgress: 45, actualProgress: 42 },
  { id: 'm16', name: '林 俊介',     affiliation: '協力会社B',   role: 'インフラ',  skillLevel: 3, experienceYears:  4, specialty: 'クラウド',   weakness: 'ドキュメント', costPerMonth:  92, utilization: 0, condition: 65, motivation: 60, isSiloed: true,  reportedProgress: 40, actualProgress: 30 },
  { id: 'm17', name: '岡本 愛',     affiliation: 'SES（客先常駐）', role: 'テスター', skillLevel: 1, experienceYears: 1, specialty: '手動テスト', weakness: '自動化全般', costPerMonth:  72, utilization: 0, condition: 52, motivation: 46, isSiloed: false, reportedProgress: 30, actualProgress: 18 },
  { id: 'm18', name: '木村 宏',     affiliation: '自社プロパー', role: 'SE',       skillLevel: 4, experienceYears: 11, specialty: '基本設計',   weakness: 'コスト交渉', costPerMonth: 118, utilization: 0, condition: 68, motivation: 60, isSiloed: false, reportedProgress: 55, actualProgress: 48 },
  { id: 'm19', name: '西田 香',     affiliation: '協力会社A',   role: 'デザイナー', skillLevel: 3, experienceYears: 4, specialty: 'UIデザイン', weakness: 'バックエンド連携', costPerMonth:  88, utilization: 0, condition: 74, motivation: 68, isSiloed: false, reportedProgress: 45, actualProgress: 40 },
  { id: 'm20', name: '橋本 修',     affiliation: 'SES（客先常駐）', role: 'PG',    skillLevel: 2, experienceYears: 3, specialty: 'バッチ処理', weakness: 'ドキュメント', costPerMonth:  84, utilization: 0, condition: 58, motivation: 52, isSiloed: false, reportedProgress: 50, actualProgress: 32 },

  // ── Ultra add (m21–m50) ───────────────────────────────────────────
  { id: 'm21', name: '加藤 良一',   affiliation: '自社プロパー', role: 'PM',       skillLevel: 5, experienceYears: 18, specialty: 'ポートフォリオ管理', weakness: '技術詳細', costPerMonth: 155, utilization: 0, condition: 82, motivation: 75, isSiloed: false, reportedProgress: 55, actualProgress: 52 },
  { id: 'm22', name: '清水 敦',     affiliation: '協力会社C',   role: 'SE',       skillLevel: 3, experienceYears:  6, specialty: '詳細設計',   weakness: 'テスト',     costPerMonth:  92, utilization: 0, condition: 70, motivation: 64, isSiloed: false, reportedProgress: 45, actualProgress: 38 },
  { id: 'm23', name: '池田 勝',     affiliation: 'オフショア',  role: 'PG',       skillLevel: 2, experienceYears:  4, specialty: '実装',       weakness: '日本語仕様', costPerMonth:  55, utilization: 0, condition: 60, motivation: 55, isSiloed: true,  reportedProgress: 40, actualProgress: 25 },
  { id: 'm24', name: '藤田 光雄',   affiliation: '自社プロパー', role: 'インフラ',  skillLevel: 4, experienceYears:  9, specialty: 'ネットワーク', weakness: 'アプリ層',  costPerMonth: 112, utilization: 0, condition: 80, motivation: 72, isSiloed: false, reportedProgress: 50, actualProgress: 47 },
  { id: 'm25', name: '岡田 修',     affiliation: '協力会社B',   role: 'DBA',      skillLevel: 3, experienceYears:  7, specialty: 'パフォーマンス', weakness: '要件定義', costPerMonth:  98, utilization: 0, condition: 72, motivation: 66, isSiloed: false, reportedProgress: 45, actualProgress: 40 },
  { id: 'm26', name: '石川 健太',   affiliation: 'オフショア',  role: 'PG',       skillLevel: 1, experienceYears:  1, specialty: '実装',       weakness: '設計理解',   costPerMonth:  48, utilization: 0, condition: 55, motivation: 50, isSiloed: true,  reportedProgress: 35, actualProgress: 15 },
  { id: 'm27', name: '後藤 晃',     affiliation: '自社プロパー', role: 'QA',       skillLevel: 3, experienceYears:  6, specialty: '品質計画',   weakness: '開発経験',   costPerMonth:  98, utilization: 0, condition: 78, motivation: 70, isSiloed: false, reportedProgress: 50, actualProgress: 46 },
  { id: 'm28', name: '吉田 奈々',   affiliation: 'SES（客先常駐）', role: 'テスター', skillLevel: 2, experienceYears: 2, specialty: '結合テスト', weakness: '自動化',    costPerMonth:  78, utilization: 0, condition: 62, motivation: 57, isSiloed: false, reportedProgress: 38, actualProgress: 26 },
  { id: 'm29', name: '田村 清美',   affiliation: '自社プロパー', role: 'アナリスト', skillLevel: 4, experienceYears: 10, specialty: '要件整理',  weakness: '実装経験',   costPerMonth: 115, utilization: 0, condition: 82, motivation: 76, isSiloed: false, reportedProgress: 52, actualProgress: 48 },
  { id: 'm30', name: '長谷川 優子', affiliation: '協力会社C',   role: 'SE',       skillLevel: 3, experienceYears:  5, specialty: '画面設計',   weakness: 'DB設計',     costPerMonth:  90, utilization: 0, condition: 70, motivation: 63, isSiloed: false, reportedProgress: 45, actualProgress: 37 },
  { id: 'm31', name: '小川 悠',     affiliation: 'オフショア',  role: 'PG',       skillLevel: 2, experienceYears:  3, specialty: 'API開発',    weakness: '日本語仕様', costPerMonth:  52, utilization: 0, condition: 58, motivation: 52, isSiloed: true,  reportedProgress: 40, actualProgress: 24 },
  { id: 'm32', name: '中島 千春',   affiliation: '自社プロパー', role: 'デザイナー', skillLevel: 4, experienceYears: 7, specialty: 'UXデザイン', weakness: 'バックエンド', costPerMonth: 105, utilization: 0, condition: 80, motivation: 74, isSiloed: false, reportedProgress: 50, actualProgress: 46 },
  { id: 'm33', name: '三浦 みな',   affiliation: 'SES（客先常駐）', role: 'テスター', skillLevel: 2, experienceYears: 1, specialty: '手動テスト', weakness: 'ツール活用', costPerMonth:  75, utilization: 0, condition: 56, motivation: 50, isSiloed: false, reportedProgress: 32, actualProgress: 20 },
  { id: 'm34', name: '桐島 れいな', affiliation: '協力会社A',   role: 'SE',       skillLevel: 3, experienceYears:  4, specialty: 'バックエンド', weakness: 'UI連携',   costPerMonth:  90, utilization: 0, condition: 68, motivation: 62, isSiloed: false, reportedProgress: 45, actualProgress: 36 },
  { id: 'm35', name: '安田 彩花',   affiliation: '自社プロパー', role: 'QA',       skillLevel: 3, experienceYears:  5, specialty: '自動テスト', weakness: '要件理解',   costPerMonth:  98, utilization: 0, condition: 76, motivation: 70, isSiloed: false, reportedProgress: 50, actualProgress: 45 },
  { id: 'm36', name: '新井 紀子',   affiliation: '自社プロパー', role: 'PL',       skillLevel: 5, experienceYears: 13, specialty: 'チームビルディング', weakness: '技術詳細', costPerMonth: 138, utilization: 0, condition: 78, motivation: 72, isSiloed: false, reportedProgress: 55, actualProgress: 50 },
  { id: 'm37', name: '大谷 千恵',   affiliation: '協力会社C',   role: 'SE',       skillLevel: 3, experienceYears:  6, specialty: '内部設計',   weakness: 'コスト感覚', costPerMonth:  92, utilization: 0, condition: 70, motivation: 62, isSiloed: false, reportedProgress: 42, actualProgress: 35 },
  { id: 'm38', name: '若林 瞳',     affiliation: 'SES（客先常駐）', role: 'PG',    skillLevel: 2, experienceYears:  2, specialty: 'フロントエンド', weakness: '設計', costPerMonth:  80, utilization: 0, condition: 60, motivation: 54, isSiloed: false, reportedProgress: 38, actualProgress: 25 },
  { id: 'm39', name: '黒田 有希',   affiliation: '自社プロパー', role: 'インフラ',  skillLevel: 4, experienceYears:  8, specialty: 'セキュリティ', weakness: '開発コード', costPerMonth: 115, utilization: 0, condition: 80, motivation: 73, isSiloed: false, reportedProgress: 48, actualProgress: 45 },
  { id: 'm40', name: '松田 麗子',   affiliation: '協力会社B',   role: 'アナリスト', skillLevel: 3, experienceYears: 5, specialty: '業務フロー分析', weakness: '技術詳細', costPerMonth:  90, utilization: 0, condition: 72, motivation: 65, isSiloed: false, reportedProgress: 45, actualProgress: 38 },
  { id: 'm41', name: '青木 拓',     affiliation: 'オフショア',  role: 'PG',       skillLevel: 1, experienceYears:  1, specialty: 'バッチ処理', weakness: '日本語仕様', costPerMonth:  45, utilization: 0, condition: 48, motivation: 42, isSiloed: true,  reportedProgress: 30, actualProgress: 12 },
  { id: 'm42', name: '金子 誠司',   affiliation: '自社プロパー', role: 'SE',       skillLevel: 4, experienceYears: 10, specialty: 'API設計',    weakness: 'UI経験',     costPerMonth: 118, utilization: 0, condition: 78, motivation: 70, isSiloed: false, reportedProgress: 50, actualProgress: 46 },
  { id: 'm43', name: '榎本 誠',     affiliation: '協力会社A',   role: 'DBA',      skillLevel: 3, experienceYears:  6, specialty: 'クエリ最適化', weakness: 'ドキュメント', costPerMonth:  98, utilization: 0, condition: 72, motivation: 66, isSiloed: false, reportedProgress: 45, actualProgress: 40 },
  { id: 'm44', name: '浅野 香里',   affiliation: 'SES（客先常駐）', role: 'テスター', skillLevel: 2, experienceYears: 2, specialty: 'システムテスト', weakness: '自動化', costPerMonth:  76, utilization: 0, condition: 58, motivation: 52, isSiloed: false, reportedProgress: 35, actualProgress: 22 },
  { id: 'm45', name: '野村 浩之',   affiliation: '協力会社B',   role: 'PM',       skillLevel: 4, experienceYears: 12, specialty: 'スケジュール管理', weakness: '顧客対応', costPerMonth: 130, utilization: 0, condition: 74, motivation: 68, isSiloed: false, reportedProgress: 55, actualProgress: 50 },
  { id: 'm46', name: '竹内 里奈',   affiliation: '自社プロパー', role: 'デザイナー', skillLevel: 3, experienceYears: 4, specialty: '画面デザイン', weakness: 'バックエンド', costPerMonth:  95, utilization: 0, condition: 78, motivation: 72, isSiloed: false, reportedProgress: 50, actualProgress: 46 },
  { id: 'm47', name: '島田 寛之',   affiliation: 'オフショア',  role: 'PG',       skillLevel: 2, experienceYears:  3, specialty: 'データ変換',  weakness: '仕様理解',  costPerMonth:  50, utilization: 0, condition: 56, motivation: 50, isSiloed: true,  reportedProgress: 38, actualProgress: 22 },
  { id: 'm48', name: '横山 美穂',   affiliation: 'SES（客先常駐）', role: 'QA',    skillLevel: 2, experienceYears:  2, specialty: 'バグ管理',   weakness: '設計理解',   costPerMonth:  76, utilization: 0, condition: 60, motivation: 55, isSiloed: false, reportedProgress: 35, actualProgress: 24 },
  { id: 'm49', name: '菊地 幸男',   affiliation: '協力会社C',   role: 'インフラ',  skillLevel: 3, experienceYears:  5, specialty: 'サーバー管理', weakness: 'クラウド',  costPerMonth:  90, utilization: 0, condition: 68, motivation: 62, isSiloed: false, reportedProgress: 42, actualProgress: 36 },
  { id: 'm50', name: '本田 涼子',   affiliation: '自社プロパー', role: 'アナリスト', skillLevel: 5, experienceYears: 14, specialty: '経営戦略分析', weakness: '現場詳細', costPerMonth: 148, utilization: 0, condition: 85, motivation: 80, isSiloed: false, reportedProgress: 55, actualProgress: 53 },
];

export const teamSizeByDifficulty: Record<string, number> = {
  easy: 5,
  normal: 10,
  hard: 20,
  ultra: 50,
};
